/**
 * Shared (browser + server) pieces of the chunked smart-import pipeline:
 * flattening an extracted payload into ordered rows, splitting those rows
 * into upload chunks, per-row validation, and the user-facing message
 * formats. No server or DOM dependencies — both sides import this file.
 */
import type {
  ExtractedWarehouse,
  ExtractedSupplier,
  ExtractedProduct,
  ExtractedInventory,
  ExtractedPurchaseOrder,
  ExtractedTransaction,
  ImportCommitPayload,
} from "./types";

export const CHUNK_MAX_ROWS = 2000;
// Leaves headroom under next.config.ts's 2MB serverActions.bodySizeLimit for
// the action envelope. Normal rows are ~100-200 bytes, so 2,000 rows sit far
// below this; the byte cap only kicks in for rows with very long text.
export const CHUNK_MAX_BYTES = 1_500_000;
const MAX_TEXT_LENGTH = 500;

// Dependency order: the commit step writes entities in exactly this order.
export const IMPORT_ENTITIES = [
  "warehouse",
  "supplier",
  "product",
  "inventory",
  "purchase_order",
  "transaction",
] as const;
export type ImportEntity = (typeof IMPORT_ENTITIES)[number];

export const ENTITY_LABELS: Record<ImportEntity, string> = {
  warehouse: "warehouses",
  supplier: "suppliers",
  product: "products",
  inventory: "stock positions",
  purchase_order: "purchase orders",
  transaction: "transactions",
};

export type StagedTransaction = ExtractedTransaction & { importKey: string };

export type StagedRowData =
  | ExtractedWarehouse
  | ExtractedSupplier
  | ExtractedProduct
  | ExtractedInventory
  | ExtractedPurchaseOrder
  | StagedTransaction;

export interface StagedRow {
  entity: ImportEntity;
  /** 1-based position within its entity's list — the "Row N" users see. */
  rowNumber: number;
  data: StagedRowData;
}

export interface ImportChunk {
  index: number;
  rows: StagedRow[];
}

/**
 * The idempotency key for an imported transaction: its content plus its
 * occurrence number among identical rows in the same file. Re-importing the
 * same file reproduces the same keys (so nothing is duplicated), while two
 * genuinely identical movements within one file stay distinct (#1, #2).
 * Plain text rather than a hash, so there's no collision risk.
 */
function withImportKeys(transactions: ExtractedTransaction[]): StagedTransaction[] {
  const seen = new Map<string, number>();
  return transactions.map((t) => {
    const base = `${t.sku}|${t.warehouseCode}|${t.date}|${t.direction}|${t.quantity}`;
    const occurrence = (seen.get(base) ?? 0) + 1;
    seen.set(base, occurrence);
    return { ...t, importKey: `${base}#${occurrence}` };
  });
}

/** Flattens a payload into rows in dependency order. */
export function flattenPayload(payload: Omit<ImportCommitPayload, "skuDuplicateResolution" | "clearExisting">): StagedRow[] {
  const rows: StagedRow[] = [];
  const push = (entity: ImportEntity, items: StagedRowData[]) => {
    items.forEach((data, i) => rows.push({ entity, rowNumber: i + 1, data }));
  };
  // Strip UI-only flags (isAutoGeneratedCode, supplierName…) so they don't
  // bloat the upload.
  push(
    "warehouse",
    payload.warehouses.map(({ code, name, capacityUnits, referenceOnly }) => ({ code, name, capacityUnits, ...(referenceOnly ? { referenceOnly } : {}) }))
  );
  push(
    "supplier",
    payload.suppliers.map(({ supplierId, name, leadTimeDays, email, leadTimeMissing, referenceOnly }) => ({
      supplierId,
      name,
      leadTimeDays,
      email,
      leadTimeMissing: leadTimeMissing ?? false,
      ...(referenceOnly ? { referenceOnly } : {}),
    }))
  );
  push(
    "product",
    payload.products.map(({ sku, name, category, unitCost, supplierId, referenceOnly }) => ({
      sku,
      name,
      category,
      unitCost,
      supplierId,
      ...(referenceOnly ? { referenceOnly } : {}),
    }))
  );
  push("inventory", payload.inventory);
  push("purchase_order", payload.purchaseOrders);
  push("transaction", withImportKeys(payload.transactions));
  return rows;
}

/**
 * Splits rows into chunks of at most `maxRows` rows and roughly `maxBytes`
 * of JSON each. A single row is never split.
 */
export function buildChunks(rows: StagedRow[], maxRows = CHUNK_MAX_ROWS, maxBytes = CHUNK_MAX_BYTES): ImportChunk[] {
  const chunks: ImportChunk[] = [];
  let current: StagedRow[] = [];
  let currentBytes = 0;
  for (const row of rows) {
    const bytes = JSON.stringify(row).length + 1;
    if (current.length > 0 && (current.length >= maxRows || currentBytes + bytes > maxBytes)) {
      chunks.push({ index: chunks.length, rows: current });
      current = [];
      currentBytes = 0;
    }
    current.push(row);
    currentBytes += bytes;
  }
  if (current.length > 0) chunks.push({ index: chunks.length, rows: current });
  return chunks;
}

async function sha256Hex(text: string): Promise<string> {
  const digest = await globalThis.crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Identifies "the same upload" so a re-selected file can resume. Hashes each
 * chunk separately, then the list of hashes — never builds one giant string
 * for the whole file.
 */
export async function fingerprintChunks(chunks: ImportChunk[], clearExisting: boolean): Promise<string> {
  const chunkHashes: string[] = [];
  for (const chunk of chunks) chunkHashes.push(await sha256Hex(JSON.stringify(chunk.rows)));
  return sha256Hex(`${clearExisting ? "replace" : "merge"}:${chunkHashes.join(",")}`);
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

/** "Row N, column X: problem", prefixed with the chunk when known. */
export function formatRowError(opts: {
  chunkIndex?: number;
  totalChunks?: number;
  entity: ImportEntity;
  rowNumber: number;
  column: string;
  problem: string;
}): string {
  const where =
    opts.chunkIndex !== undefined
      ? `Chunk ${opts.chunkIndex + 1}${opts.totalChunks ? ` of ${opts.totalChunks}` : ""}, `
      : "";
  return `${where}${ENTITY_LABELS[opts.entity]} row ${opts.rowNumber.toLocaleString("en-US")}, column "${opts.column}": ${opts.problem}`;
}

export function formatLimitNote(rows: number, limit: number): string {
  return `This file has ${rows.toLocaleString("en-US")} rows. Your plan allows ${limit.toLocaleString("en-US")} per import. Split the file or upgrade.`;
}

export function formatLimitHint(limit: number): string {
  return `Up to ${limit.toLocaleString("en-US")} rows per import`;
}

// ---------------------------------------------------------------------------
// Per-row validation (server re-runs this on every chunk — never trusts the
// browser's extractor)
// ---------------------------------------------------------------------------

type Problem = { column: string; problem: string };

function checkText(obj: Record<string, unknown>, key: string, required: boolean): Problem | null {
  const v = obj[key];
  if (v === null || v === undefined || v === "") {
    return required ? { column: key, problem: "is required but empty." } : null;
  }
  if (typeof v !== "string") return { column: key, problem: `expected text, got ${JSON.stringify(v)}.` };
  if (v.length > MAX_TEXT_LENGTH) return { column: key, problem: `is ${v.length} characters long (max ${MAX_TEXT_LENGTH}).` };
  return null;
}

function checkNumber(obj: Record<string, unknown>, key: string, opts: { integer?: boolean; min?: number; optional?: boolean }): Problem | null {
  const v = obj[key];
  if (opts.optional && (v === null || v === undefined)) return null;
  if (typeof v !== "number" || !Number.isFinite(v)) return { column: key, problem: `${JSON.stringify(v)} is not a number.` };
  if (opts.integer && !Number.isInteger(v)) return { column: key, problem: `${v} must be a whole number.` };
  if (opts.min !== undefined && v < opts.min) return { column: key, problem: `${v} is below the minimum of ${opts.min}.` };
  if (Math.abs(v) > 2_000_000_000) return { column: key, problem: `${v} is out of range.` };
  return null;
}

function checkDate(obj: Record<string, unknown>, key: string, required: boolean): Problem | null {
  const v = obj[key];
  if (v === null || v === undefined) return required ? { column: key, problem: "is required but empty." } : null;
  if (typeof v !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(v) || Number.isNaN(Date.parse(`${v}T00:00:00Z`))) {
    return { column: key, problem: `${JSON.stringify(v)} is not a valid date (expected YYYY-MM-DD).` };
  }
  return null;
}

export function validateRow(row: StagedRow): Problem | null {
  if (!row || typeof row !== "object" || !IMPORT_ENTITIES.includes(row.entity)) {
    return { column: "entity", problem: "unknown row type." };
  }
  if (!Number.isInteger(row.rowNumber) || row.rowNumber < 1) return { column: "row", problem: "invalid row number." };
  const d = row.data as unknown as Record<string, unknown>;
  if (!d || typeof d !== "object") return { column: "data", problem: "row is empty." };

  const checks: (() => Problem | null)[] = [];
  switch (row.entity) {
    case "warehouse":
      checks.push(
        () => checkText(d, "code", true),
        () => checkText(d, "name", true),
        // null = the file gave no capacity; saved as unknown, never a placeholder.
        () => checkNumber(d, "capacityUnits", { integer: true, min: 0, optional: true })
      );
      break;
    case "supplier":
      checks.push(
        () => checkText(d, "supplierId", true),
        () => checkText(d, "name", true),
        () => checkNumber(d, "leadTimeDays", { integer: true, min: 0 }),
        () => checkText(d, "email", false)
      );
      break;
    case "product":
      checks.push(
        () => checkText(d, "sku", true),
        () => checkText(d, "name", true),
        () => checkText(d, "category", false),
        // null = the file has no cost: allowed, never defaulted (the commit
        // keeps an existing product's cost and refuses to create one without).
        () => (d.unitCost === null ? null : checkNumber(d, "unitCost", { min: 0 })),
        () => checkText(d, "supplierId", true)
      );
      break;
    case "inventory":
      checks.push(
        () => checkText(d, "sku", true),
        () => checkText(d, "warehouseCode", true),
        () => checkNumber(d, "quantityOnHand", { integer: true })
      );
      break;
    case "purchase_order":
      checks.push(
        () => checkText(d, "poNumber", true),
        () => checkText(d, "supplierId", true),
        () => checkText(d, "sku", true),
        () => checkNumber(d, "quantity", { integer: true, min: 0 }),
        () => checkNumber(d, "unitPrice", { min: 0 }),
        () => checkDate(d, "orderDate", true),
        () => checkDate(d, "expectedDate", true),
        () => checkDate(d, "receivedDate", false)
      );
      break;
    case "transaction":
      checks.push(
        () => checkText(d, "sku", true),
        () => checkText(d, "warehouseCode", true),
        () => checkNumber(d, "quantity", { integer: true, min: 0 }),
        () => (d.direction === "IN" || d.direction === "OUT" ? null : { column: "direction", problem: `${JSON.stringify(d.direction)} must be IN or OUT.` }),
        () => checkDate(d, "date", true),
        () => checkText(d, "importKey", true)
      );
      break;
  }
  for (const check of checks) {
    const p = check();
    if (p) return p;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Server responses (shared so the browser orchestrator can type them)
// ---------------------------------------------------------------------------

export type ImportCounts = Record<"warehouses" | "suppliers" | "products" | "inventory" | "purchaseOrders" | "transactions", number>;

export type ImportFailure = {
  ok: false;
  error: string;
  /** Present when the failure is the plan's row limit — shown as a neutral note, not an error. */
  limitExceeded?: { rows: number; limit: number };
};

export type BeginResult = { ok: true; sessionId: string; receivedChunks: number[]; resumed: boolean } | ImportFailure;

export type StageResult = { ok: true; receivedChunks: number } | ImportFailure;

export type StatusResult =
  | { ok: true; status: string; totalRows: number; totalChunks: number; receivedChunks: number[] }
  | ImportFailure;

export type CommitResult =
  | {
      ok: true;
      counts: ImportCounts;
      /** Transactions already present from an earlier import of the same rows. */
      duplicateTransactionsSkipped: number;
      /** Demo org: everything ran for real, then was rolled back. */
      simulated: boolean;
    }
  | ImportFailure;
