export type CanonicalFieldId =
  | "sku"
  | "product_name"
  | "category"
  | "unit_cost"
  | "supplier_name"
  | "supplier_id"
  | "supplier_lead_time"
  | "supplier_email"
  | "warehouse_code"
  | "warehouse_name"
  | "warehouse_capacity"
  | "quantity_on_hand"
  | "po_number"
  | "order_date"
  | "expected_date"
  | "received_date"
  | "po_quantity"
  | "po_unit_price"
  | "transaction_qty"
  | "transaction_direction"
  | "transaction_date";

export interface CanonicalFieldDef {
  id: CanonicalFieldId;
  label: string;
  category: "product" | "supplier" | "warehouse" | "inventory" | "purchase_order" | "transaction";
  description: string;
  requiredForEntity?: boolean;
}

export interface RawParsedSheet {
  name: string;
  headerRowIndex: number;
  headers: string[];
  rawRows: (string | number | boolean | Date | null)[][];
  rowCount: number;
  columnCount: number;
}

export interface ColumnMappingItem {
  rawHeader: string;
  rawHeaderIndex: number;
  canonicalField: CanonicalFieldId | null; // null = ignore
  confidence: number; // 0.0 to 1.0
  matchReason: string;
  sampleValues: (string | number | null)[];
}

export interface SheetMapping {
  sheetName: string;
  headerRowIndex: number;
  mappings: ColumnMappingItem[];
}

export interface FuzzyMergeGroup {
  id: string;
  entityType: "supplier" | "warehouse";
  canonicalName: string; // recommended display name
  variants: {
    originalName: string;
    normalizedName: string;
    rowCount: number;
  }[];
  confidence: number;
  isConfirmed: boolean; // default true for confidence >= 0.85
}

export interface SkuSupplierConflict {
  sku: string;
  productName: string;
  suppliers: string[];
  selectedSupplier: string;
}

export interface ExtractedWarehouse {
  code: string;
  name: string;
  capacityUnits: number;
  isAutoGeneratedCode?: boolean;
}

export interface ExtractedSupplier {
  supplierId: string;
  name: string;
  leadTimeDays: number;
  email: string;
  isAutoGeneratedId?: boolean;
  leadTimeMissing?: boolean;
}

export interface ExtractedProduct {
  sku: string;
  name: string;
  category: string;
  unitCost: number;
  supplierId: string;
  supplierName?: string;
}

export interface ExtractedInventory {
  sku: string;
  warehouseCode: string;
  quantityOnHand: number;
}

export interface ExtractedPurchaseOrder {
  poNumber: string;
  supplierId: string;
  sku: string;
  quantity: number;
  unitPrice: number;
  orderDate: string; // ISO date
  expectedDate: string; // ISO date
  receivedDate: string | null;
}

export interface ExtractedTransaction {
  sku: string;
  warehouseCode: string;
  quantity: number;
  direction: "IN" | "OUT";
  date: string; // ISO date
}

export interface RejectedRowRecord {
  sheetName: string;
  rowIndex: number;
  rawRow: Record<string, unknown>;
  reason: string;
}

export interface ExtractionPreview {
  warehouses: ExtractedWarehouse[];
  suppliers: ExtractedSupplier[];
  products: ExtractedProduct[];
  inventory: ExtractedInventory[];
  purchaseOrders: ExtractedPurchaseOrder[];
  transactions: ExtractedTransaction[];
  mergeGroups: FuzzyMergeGroup[];
  skuConflicts: SkuSupplierConflict[];
  rejectedRows: RejectedRowRecord[];
  missingLeadTimeCount: number;
  missingCapacityCount: number;
  defaultWarehouseUsed: boolean;
  generatedIdsCount: number;
  totalRowsProcessed: number;
}

export type SkuDuplicateResolution = "sum" | "last";

export interface ImportCommitPayload {
  warehouses: ExtractedWarehouse[];
  suppliers: ExtractedSupplier[];
  products: ExtractedProduct[];
  inventory: ExtractedInventory[];
  purchaseOrders: ExtractedPurchaseOrder[];
  transactions: ExtractedTransaction[];
  skuDuplicateResolution: SkuDuplicateResolution;
  clearExisting?: boolean;
}

export interface ImportCommitResult {
  success: boolean;
  importedCounts: {
    warehouses: number;
    suppliers: number;
    products: number;
    inventory: number;
    purchaseOrders: number;
    transactions: number;
  };
  missingLeadTimeCount: number;
  missingCapacityCount: number;
  /** Transactions skipped because an earlier import already saved the same rows. */
  duplicateTransactionsSkipped?: number;
  /** Demo workspace: the import ran in full inside a transaction, then was rolled back. */
  simulated?: boolean;
  error?: string;
}
