export type CanonicalFieldId =
  | "sku"
  | "product_name"
  | "category"
  | "unit_cost"
  | "supplier_name"
  | "supplier_id"
  | "supplier_lead_time"
  | "supplier_email"
  | "warehouse_code"
  | "warehouse_name"
  | "warehouse_capacity"
  | "quantity_on_hand"
  | "po_number"
  | "order_date"
  | "expected_date"
  | "received_date"
  | "po_quantity"
  | "po_unit_price"
  | "transaction_qty"
  | "transaction_direction"
  | "transaction_date";

export interface CanonicalFieldDef {
  id: CanonicalFieldId;
  label: string;
  category: "product" | "supplier" | "warehouse" | "inventory" | "purchase_order" | "transaction";
  description: string;
  requiredForEntity?: boolean;
}

export interface RawParsedSheet {
  name: string;
  headerRowIndex: number;
  headers: string[];
  rawRows: (string | number | boolean | Date | null)[][];
  rowCount: number;
  columnCount: number;
}

export interface ColumnMappingItem {
  rawHeader: string;
  rawHeaderIndex: number;
  canonicalField: CanonicalFieldId | null; // null = ignore
  confidence: number; // 0.0 to 1.0
  matchReason: string;
  sampleValues: (string | number | null)[];
}

export interface SheetMapping {
  sheetName: string;
  headerRowIndex: number;
  mappings: ColumnMappingItem[];
}

export interface FuzzyMergeGroup {
  id: string;
  entityType: "supplier" | "warehouse";
  canonicalName: string; // recommended display name
  variants: {
    originalName: string;
    normalizedName: string;
    rowCount: number;
    /** Supplier ID / warehouse code this name came with, if the file had one. */
    entityId?: string;
  }[];
  confidence: number;
  /**
   * Pre-ticked only when every variant is clearly the same name (differs only
   * in case, punctuation or a legal suffix like LLC / Co). Near matches
   * (typos, abbreviations) are suggestions and stay unticked. Either way the
   * group is listed so the user can split or accept it.
   */
  isConfirmed: boolean;
  /** "same-name": case/punctuation/suffix only. "similar": typo/abbreviation suggestion. */
  matchKind?: "same-name" | "similar";
}

export interface SkuSupplierConflict {
  sku: string;
  productName: string;
  /** Resolved supplier IDs. */
  suppliers: string[];
  selectedSupplier: string;
  /** Display label per supplier ID, e.g. "Delta Components LLC (SUP-001)". */
  supplierLabels?: Record<string, string>;
}

/**
 * Two rows describe the same SKU with different details. Nothing is
 * overwritten silently: the first value is kept unless the user picks another.
 */
export interface ProductDetailConflict {
  sku: string;
  field: "name" | "category" | "unitCost";
  options: { value: string | number; sheetName: string; rowNumber: number }[];
  /** Index into options; 0 (first seen) unless the user chose otherwise. */
  selectedIndex: number;
}

/** The same SKU at the same warehouse appears on more than one stock row. */
export interface DuplicateStockPosition {
  sku: string;
  warehouseCode: string;
  quantities: number[];
}

export interface ExtractedWarehouse {
  code: string;
  name: string;
  capacityUnits: number;
  isAutoGeneratedCode?: boolean;
  /** Only mentioned (by ID / code / SKU), never described: created if missing, never used to update an existing record. */
  referenceOnly?: boolean;
}

export interface ExtractedSupplier {
  supplierId: string;
  name: string;
  leadTimeDays: number;
  email: string;
  isAutoGeneratedId?: boolean;
  leadTimeMissing?: boolean;
  /** Only mentioned (by ID / code / SKU), never described: created if missing, never used to update an existing record. */
  referenceOnly?: boolean;
}

export interface ExtractedProduct {
  sku: string;
  name: string;
  category: string;
  unitCost: number;
  supplierId: string;
  supplierName?: string;
  /** Only mentioned (by ID / code / SKU), never described: created if missing, never used to update an existing record. */
  referenceOnly?: boolean;
}

export interface ExtractedInventory {
  sku: string;
  warehouseCode: string;
  quantityOnHand: number;
}

export interface ExtractedPurchaseOrder {
  poNumber: string;
  supplierId: string;
  sku: string;
  quantity: number;
  unitPrice: number;
  orderDate: string; // ISO date
  expectedDate: string; // ISO date
  receivedDate: string | null;
}

export interface ExtractedTransaction {
  sku: string;
  warehouseCode: string;
  quantity: number;
  direction: "IN" | "OUT";
  date: string; // ISO date
}

export interface RejectedRowRecord {
  sheetName: string;
  rowIndex: number;
  rawRow: Record<string, unknown>;
  reason: string;
}

export interface ExtractionPreview {
  warehouses: ExtractedWarehouse[];
  suppliers: ExtractedSupplier[];
  products: ExtractedProduct[];
  inventory: ExtractedInventory[];
  purchaseOrders: ExtractedPurchaseOrder[];
  transactions: ExtractedTransaction[];
  mergeGroups: FuzzyMergeGroup[];
  skuConflicts: SkuSupplierConflict[];
  productConflicts: ProductDetailConflict[];
  duplicateStockPositions: DuplicateStockPosition[];
  rejectedRows: RejectedRowRecord[];
  missingLeadTimeCount: number;
  missingCapacityCount: number;
  defaultWarehouseUsed: boolean;
  generatedIdsCount: number;
  totalRowsProcessed: number;
}

export type SkuDuplicateResolution = "sum" | "last";

export interface ImportCommitPayload {
  warehouses: ExtractedWarehouse[];
  suppliers: ExtractedSupplier[];
  products: ExtractedProduct[];
  inventory: ExtractedInventory[];
  purchaseOrders: ExtractedPurchaseOrder[];
  transactions: ExtractedTransaction[];
  skuDuplicateResolution: SkuDuplicateResolution;
  clearExisting?: boolean;
}

export interface ImportCommitResult {
  success: boolean;
  importedCounts: {
    warehouses: number;
    suppliers: number;
    products: number;
    inventory: number;
    purchaseOrders: number;
    transactions: number;
  };
  missingLeadTimeCount: number;
  missingCapacityCount: number;
  /** Transactions skipped because an earlier import already saved the same rows. */
  duplicateTransactionsSkipped?: number;
  /** Demo workspace: the import ran in full inside a transaction, then was rolled back. */
  simulated?: boolean;
  error?: string;
}
