import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { SITE_NAME, SITE_URL, CONTACT_EMAIL } from "@/lib/site-config";

const TITLE = `Privacy Policy | ${SITE_NAME}`;
const DESCRIPTION = `How ${SITE_NAME} collects, uses, stores, and protects your data.`;
const LAST_UPDATED = "September 18, 2026";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/privacy` },
  robots: { index: true, follow: true },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${SITE_URL}/privacy`,
    siteName: SITE_NAME,
    type: "website",
  },
};

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-h3 text-(--color-text-primary)">{title}</h2>
      <div className="space-y-3 text-body text-(--color-text-secondary)">{children}</div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <p className="text-small font-medium uppercase tracking-wide text-(--color-text-muted)">Legal</p>
      <h1 className="mt-2 text-h1 text-(--color-text-primary)">Privacy Policy</h1>
      <p className="mt-2 text-small text-(--color-text-muted)">Last updated: {LAST_UPDATED}</p>

      <div className="mt-10 space-y-10">
        <Section title="Overview">
          <p>
            This policy explains what data {SITE_NAME} collects when you use our website and application, how we
            use it, how it&apos;s stored, and the choices you have. It applies to visitors of our marketing site and
            to organizations (&quot;customers&quot;) using the {SITE_NAME} dashboard.
          </p>
        </Section>

        <Section title="Data we collect">
          <p>
            <strong className="text-(--color-text-primary)">Account &amp; identity data</strong> — name, email
            address, and organization membership, collected when you sign up or are invited to a workspace. Sign-in
            and account management is handled by our authentication provider, Clerk.
          </p>
          <p>
            <strong className="text-(--color-text-primary)">Operational data you provide</strong> — the product
            catalog, inventory levels, supplier records, purchase orders, and transaction history you import or
            connect so the dashboard can calculate health scores, alerts, and reorder recommendations. This data
            belongs to you; we process it on your behalf to provide the service.
          </p>
          <p>
            <strong className="text-(--color-text-primary)">Usage data</strong> — standard web request logs (IP
            address, browser type, pages visited, timestamps) generated by normal operation of our hosting
            infrastructure.
          </p>
          <p>
            <strong className="text-(--color-text-primary)">Demo mode</strong> — if you use the live demo
            (<code>?demo=true</code>), we set a cookie to keep you in demo mode. Demo actions are simulated and never
            written to the canonical dataset; no personal data is required to use the demo.
          </p>
        </Section>

        <Section title="How we use data">
          <ul className="list-disc space-y-2 pl-5">
            <li>To provide, maintain, and secure the dashboard for your organization.</li>
            <li>To calculate the health scores, alerts, and recommendations that are the core of the product.</li>
            <li>To communicate with you about your account, service changes, or support requests.</li>
            <li>To monitor, debug, and improve reliability of the application.</li>
          </ul>
          <p>We do not sell customer data, and we do not use your operational data to train third-party AI models.</p>
        </Section>

        <Section title="Where data is stored and processed">
          <p>
            The application runs on Vercel, and the primary database is a PostgreSQL instance hosted on Neon. See
            our{" "}
            <Link href="/security" className="font-medium text-(--color-brand) hover:underline">
              Security page
            </Link>{" "}
            for infrastructure and encryption details. Each organization&apos;s data is logically isolated from
            other organizations.
          </p>
          {/* TODO: add the specific Vercel deployment region(s) and Neon
              project region here once confirmed. */}
        </Section>

        <Section title="Who we share data with">
          <p>
            We share data only with the service providers (&quot;subprocessors&quot;) needed to run {SITE_NAME}:
            Vercel (application hosting and compute), Neon (database hosting), and Clerk (authentication). We do not
            share your operational data with anyone else, except where required by law.
          </p>
          {/* TODO: keep this list in sync with the Security page's
              Subprocessors section if a new one is added (e.g. an
              email/SMS provider for alerts, or a payments processor). */}
        </Section>

        <Section title="Data retention and deletion">
          <p>
            We retain your data for as long as your organization has an active account. You can request deletion or
            export of your organization&apos;s data at any time by emailing{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="font-medium text-(--color-brand) hover:underline">
              {CONTACT_EMAIL}
            </a>
            . We&apos;ll confirm the request and let you know once it&apos;s complete.
          </p>
          {/* TODO: commit to and publish a specific turnaround SLA once decided. */}
        </Section>

        <Section title="Your rights">
          <p>
            Depending on where you live, you may have rights to access, correct, export, or delete your personal
            data, and to object to or restrict certain processing. To exercise any of these rights, contact us at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="font-medium text-(--color-brand) hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        <Section title="Children's privacy">
          <p>{SITE_NAME} is a business tool and is not directed at, or intended for use by, children.</p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            We may update this policy from time to time. Material changes will be reflected by updating the
            &quot;Last updated&quot; date above.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about this policy? Email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="font-medium text-(--color-brand) hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
          {/* TODO: add registered legal entity name, mailing address, and
              governing-law jurisdiction once confirmed. */}
        </Section>
      </div>
    </div>
  );
}
